server:
  port: 8081

spring:
  application:
    name: config-server

  cloud:
    config:
      enabled: true
      server:
        git:
          uri: https://github.com/FrancoLacourt/config-server-test.git
          search-paths: config-data
          username: ${GIT_USERNAME}
          password: ${GIT_PASSWORD}